import { randomColor } from "lib/utils";

export const sections = [
  {
    title: "May",
    data: [
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() }
    ]
  },
  {
    title: "April",
    data: [
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() }
    ]
  },
  {
    title: "March",
    data: [
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() }
    ]
  },
  {
    title: "February",
    data: [
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() }
    ]
  },
  {
    title: "January",
    data: [
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item1", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() },
      { title: "item2", color: randomColor() }
    ]
  }
];
