import uuid from "uuid/v4";
import { randomColor } from "lib/utils";

export const sections = [
  {
    title: "May",
    sectionIndex: 0,
    data: [
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() }
    ]
  },
  {
    title: "April",
    sectionIndex: 1,
    data: [
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() }
    ]
  },
  {
    title: "March",
    sectionIndex: 2,
    data: [
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() }
    ]
  },
  {
    title: "February",
    sectionIndex: 3,
    data: [
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() }
    ]
  },
  {
    title: "January",
    sectionIndex: 4,
    data: [
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item1", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() },
      { title: "item2", color: randomColor(), id: uuid() }
    ]
  }
];
